version: "3.3"
services:
    db:
        image: 'postgres:latest'
        ports:
            - 8001:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password1!
          POSTGRES_DB: aurora

    hub:
        image: selenium/hub
        container_name: "hub"
        ports:
            - "8002:4444"
    firefox:
        image: selenium/node-firefox
        depends_on:
            - hub
        environment:
          SE_EVENT_BUS_HOST: hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_NODE_GRID_URL: http://hub:4444

          SCREEN_WIDTH: 1920
          SCREEN_HEIGHT: 1080

          SE_NODE_MAX_SESSIONS: 4
    web:
        image: yaroslavholota/aurora:latest
        ports:
            - "8000:80"
        environment:
            ConnectionStrings:MainDb: User ID=postgres;Password=password1!;Host=db;Port=5432;Database=aurora;
            Selenium:SeleniumLocation: http://selenium:4444/wd/hub
        depends_on:
            - db
            - selenium