version: "3.3"
services:
    db:
        image: 'postgres:latest'
        ports:
            - 8001:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password1!
          POSTGRES_DB: aurora


    selenium:
        image: "selenium/standalone-firefox:4.2.2"
        ports:
            - "8002:4444"