version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "password1!"
            ACCEPT_EULA: "Y"
    selenium:
        image: "selenium/standalone-firefox:4.2.2"
        ports:
            - "4444:4444"
    web:
        image: yaroslavholota/aurora:latest
        ports:
            - "8000:80"
        environment:
            ConnectionStrings:MainDb: Server=db;Database=master;User=SA;Password=password1!;
            Selenium:SeleniumLocation: http://selenium:4444/wd/hub
        depends_on:
            - db
            - selenium