version: "3.3"
services:
    db:
        image: arm64v8/postgres
        ports:
            - 8001:5432
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password1!
          POSTGRES_DB: aurora

    selenium:
        image: seleniarm/standalone-firefox
        ports:
            - "8002:4444"
    web:
        build: 
            context: .
            dockerfile: Dockerfile-arm64
        ports:
            - "8000:80"
        environment:
            ConnectionStrings:MainDb: User ID=postgres;Password=password1!;Host=db;Port=5432;Database=aurora;
            Selenium:SeleniumLocation: http://selenium:4444/wd/hub

        depends_on:
            - db
            - selenium

        restart: on-failure:5